// Generated by analyze.py from style_profile.json. Aggregate figures only.
window.JAM_STYLE = {
 "tempo_fast_range": [
  146.631,
  178.206
 ],
 "tempo_fast_median": 159.052,
 "minor_song_share": 0.375,
 "chord_color": {
  "seventh": 0.573,
  "ninth": 0.075,
  "eleventh": 0.118,
  "sixth": 0.031,
  "sus": 0.432,
  "any": 0.591
 },
 "odd_meter_share": 0.11,
 "swing_ratio": 1.009,
 "syncopation_index": 0.432,
 "breakdowns_per_min": 0.497,
 "builds_per_min": 0.676,
 "sharp_drops_per_min": 0.88,
 "half_time_share": 0.005,
 "bass_share": 0.692,
 "brightness_hz": 1875.249
};
